linters:
  enable:
    - asasalint
    - bodyclose
    - depguard
    - exportloopref
    - gochecknoinits
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - govet
    - misspell
    - nakedret
    - prealloc
    - unconvert
    - unparam
  disable:
    - errcheck
